export const TEST_IDS = {
  discoverScreen: "discover-screen",
  topNav: "top-nav",
  searchBar: "search-bar",
  alphabetListSection: "alphabet-list-section",
  bottomNav: "bottom-nav",
  dateTimePicker: "date-time-picker",
  iconHome: "icon-home",
  dropDownPicker: "dropdown-picker",
  selectorButton: "selector-button",
  PlayButtonBar: "play-button-bar",
  frequencySelector: "frequency-selector",
  clearButton: "clear-button",
  selectTimeButton: "select-time-button",
  flatlist: "flatlist",
  autoScrollingQuotesList: "auto-scrolling-quotes-list",
  quoteContainer: "quote-container",
  playButton: "play-button",
};
