name: CI Pipeline

on: [push, pull_request]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
  lint_and_test:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Clean Git Cache
        run: git gc --prune=now && git remote prune origin

      - name: Install dependencies (if needed)
        run: yarn install --frozen-lockfile

      - name: List Contents of src/res/constants
        run: ls -l ./src/res/constants/

      - name: List installed binaries
        run: ls node_modules/.bin

      - name: Run ESLint
        run: npx eslint src --ext .js,.jsx,.ts,.tsx --fix

      - name: Clear Jest Cache
        run: yarn jest --clearCache

      - name: Run Jest Tests
        run: yarn test

  type_check:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check TypeScript Compiler
        run: |
          if ! [ -x "$(command -v npx tsc)" ]; then
            echo "TypeScript Compiler (tsc) is not installed. Installing..."
            yarn install --frozen-lockfile
          fi

      - name: Run TypeScript Compiler
        run: yarn tsc --noEmit

  build_ios:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache Yarn Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build iOS app with EAS
        run: eas build --platform ios --non-interactive
