name: CI Pipeline

on: [push, pull_request]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

  lint_and_test:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Clean Git Cache
        run: git gc --prune=now && git remote prune origin

      - name: List Contents of src/res/constants
        run: ls -l ./src/res/constants/

      - name: List installed binaries
        run: ls node_modules/.bin

      - name: Run ESLint
        run: npx eslint src --ext .js,.jsx,.ts,.tsx --fix

      - name: Clear Jest Cache
        run: yarn jest --clearCache

      - name: Run Jest Tests
        run: yarn test

  type_check:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run TypeScript Compiler
        run: yarn tsc --noEmit

  build:
    needs: type_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Project
        run: yarn build
